// Author: David M. Anderson
// Built with AI assistance (Claude, Anthropic)
//
// A message Zirbe is about to send, in Zirbe's own vocabulary so the mail engine
// behind ZirbeMail stays swappable. It carries the RFC 5322 threading headers a
// reply needs and a Message-ID generated before sending, so the SMTP send and
// the Sent-folder copy share one identity and a retry can't leave a duplicate.

import Foundation

/// One outgoing message: who it's from and to, what it says, and the threading
/// headers that place it in a conversation. To and Cc are kept distinct, the way
/// a proper reply preserves them.
public struct OutgoingMessage: Sendable, Hashable {
    public var from: OutgoingAddress
    public var to: [OutgoingAddress]
    public var cc: [OutgoingAddress]
    public var subject: String
    public var textBody: String
    /// `In-Reply-To`: the message this one answers, in `<id@host>` form. Nil for
    /// a brand-new conversation that answers nothing.
    public var inReplyTo: String?
    /// `References`: the conversation's ancestry chain, oldest first, each in
    /// `<id@host>` form. Empty for a new conversation.
    public var references: [String]
    /// This message's own Message-ID, in `<id@host>` form, generated by the
    /// caller before sending so the SMTP send and the Sent-folder copy carry the
    /// same value and a retry deduplicates instead of doubling.
    public var messageID: String
    /// Files to send alongside the body, each carrying its own bytes. Empty for a
    /// plain reply or a new message; a forward fills it with the bytes of the
    /// original's attachments, refetched from the server.
    public var attachments: [OutgoingAttachment]

    public init(
        from: OutgoingAddress,
        to: [OutgoingAddress],
        cc: [OutgoingAddress] = [],
        subject: String,
        textBody: String,
        inReplyTo: String? = nil,
        references: [String] = [],
        messageID: String,
        attachments: [OutgoingAttachment] = []
    ) {
        self.from = from
        self.to = to
        self.cc = cc
        self.subject = subject
        self.textBody = textBody
        self.inReplyTo = inReplyTo
        self.references = references
        self.messageID = messageID
        self.attachments = attachments
    }
}

/// One file to send: its name, type, and the bytes themselves. ZirbeMail's own
/// type so the send path doesn't depend on SwiftMail's `Attachment`; the mapping
/// to that lives in OutgoingMapping. Forwarded attachments are always regular
/// (not inline), so there is no content-ID or inline flag here.
public struct OutgoingAttachment: Sendable, Hashable {
    public var filename: String
    public var mimeType: String
    public var data: Data

    public init(filename: String, mimeType: String, data: Data) {
        self.filename = filename
        self.mimeType = mimeType
        self.data = data
    }
}

/// An addressee on an outgoing message: the address plus an optional display
/// name. ZirbeMail's own type, so the send path doesn't depend on ZirbeCore's
/// `Participant`.
public struct OutgoingAddress: Sendable, Hashable {
    public var address: String
    public var name: String?

    public init(address: String, name: String? = nil) {
        self.address = address
        self.name = name
    }
}
